name: Deploy Flask App and Send Email

on:
  workflow_dispatch:  # Manually triggered workflow

jobs:
  build_and_run_container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t my-flask-app .

      - name: Run Container
        run: |
          docker run -d --name flask-container -p 5000:5000 my-flask-app
          
      - name: Wait for Container to Start
        run: sleep 10

      - name: Check if Container is Running
        run: |
          if docker ps | grep -q flask-container; then
            echo "CONTAINER_STATUS=running" >> $GITHUB_ENV
          else
            echo "CONTAINER_STATUS=failed" >> $GITHUB_ENV
            exit 1
          fi

  send_email:
    needs: build_and_run_container
    runs-on: ubuntu-latest
    if: success()  # Only runs if previous job succeeded
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Flask Container Deployment Successful ✅"
          body: "The Flask container is successfully running and deployed!"
          to: "raihaniqbal@kpmg.com"  # Replace with recipient email
          from: "GitHub Actions rockrocking1995@gmail.com"
          content_type: text/plain


